// <auto-generated />
using System;
using FranChallenge.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace FranChallenge.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220701165607_RestOfModels")]
    partial class RestOfModels
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("FranChallenge.Models.Appointment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<DateTime>("end")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("officeid")
                        .HasColumnType("integer");

                    b.Property<int?>("patientid")
                        .HasColumnType("integer");

                    b.Property<DateTime>("start")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("id");

                    b.HasIndex("officeid");

                    b.HasIndex("patientid");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("FranChallenge.Models.Doctor", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("FranChallenge.Models.Office", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<int>("officeNumber")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("Offices");
                });

            modelBuilder.Entity("FranChallenge.Models.Patient", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("FranChallenge.Models.Appointment", b =>
                {
                    b.HasOne("FranChallenge.Models.Office", "office")
                        .WithMany()
                        .HasForeignKey("officeid");

                    b.HasOne("FranChallenge.Models.Patient", "patient")
                        .WithMany()
                        .HasForeignKey("patientid");

                    b.Navigation("office");

                    b.Navigation("patient");
                });
#pragma warning restore 612, 618
        }
    }
}
